package com.bendaniel10.broker.storage.repository

import com.bendaniel10.broker.storage.model.BrokerProjectRuleResponse

interface BrokerProjectRuleResponseRepository : BrokerRepository<BrokerProjectRuleResponse>